apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  labels:
    app: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Modify as needed based on your Kubernetes setup
  hostPath:
    path: /mnt/data/mysql  # The host path where MySQL data will persist (adjust for your setup)
